//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphanem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMİN
    {
        public int ID { get; set; }
        public string KULLANİCİ { get; set; }
        public string SİFRE { get; set; }
        public string YETKİ { get; set; }
    }
}
